//package poormansgrep.BonusProject;
//
//import java.io.ByteArrayOutputStream;
//import java.io.PrintStream;
//
//import org.junit.After;
//import org.junit.Assert;
//import org.junit.Before;
//import org.junit.Test;
//
///**
// * Unit test for simple App.
// */
//public class AppTest {
//	private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
//
//	@Before
//	public void setUpStreams() {
//		System.setOut(new PrintStream(outContent));
//	}
//
//	@After
//	public void cleanUpStreams() {
//		System.setOut(null);
//		outContent.reset();
//	}
//
//	/**
//	 * Test method accessing output generated by System.out.println(...) calls.
//	 */
//	@Test
//	public void testApp() {
//		App.main(new String[] {}); // Calling main() method printing "Hello
//									// World!"
//		Assert.assertEquals("Hello World!", outContent.toString());
//	}
//}