package poormansgrep.BonusProject;

import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

/**
 * Unit test for simple App.
 */
public class AppTest {
   private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

   @Before
   public void setUpStreams() {
       System.setOut(new PrintStream(outContent));
   }

   @After
   public void cleanUpStreams() {
       System.setOut(null);
       outContent.reset();
   }
   
    /**
     * Test method accessing output generated by System.out.println(...) calls.
     * @throws IOException 
     * @throws FileNotFoundException 
     */
    @Test
    public void testApp() throws FileNotFoundException, IOException {
       Grep.GrepTest(new String[]{"red","D:/workspace/test.txt"});
       Assert.assertEquals("red",outContent.toString());
    }
    @Test
    public void testApp2() throws FileNotFoundException, IOException {
    	Grep.GrepTest(new String[]{"red","D:/workspace/test2.txt"});
        Assert.assertEquals("red\nred",outContent.toString());
    }
}